"""ops monitoring schema

Revision ID: c851e9878092
Revises: 0001
Create Date: 2026-10-06 23:39:07.212086

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = 'c851e9878092'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Upstream Alembic template default for an autogenerated revision with no
    # detected change. Real migrations are written in the database phase.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_alert_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('rule_code', sa.String(length=64), nullable=False, comment='规则编码'),
    sa.Column('rule_name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('alert_type', sa.String(length=64), nullable=False, comment='告警类型（CPU_HIGH/MEMORY_HIGH/SERVICE_DOWN/API_ERROR_RATE_HIGH/...）'),
    sa.Column('metric_key', sa.String(length=128), nullable=False, comment='监控指标键'),
    sa.Column('condition', sa.String(length=16), server_default=sa.text("'GT'"), nullable=False, comment='比较条件（GT/GTE/LT/LTE/EQ/NE）'),
    sa.Column('threshold', sa.Float(), nullable=False, comment='阈值（配置化，不允许硬编码）'),
    sa.Column('duration_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False, comment='持续时长（秒）'),
    sa.Column('severity', sa.String(length=32), server_default=sa.text("'WARNING'"), nullable=False, comment='严重级别（INFO/WARNING/ERROR/CRITICAL）'),
    sa.Column('scope_type', sa.String(length=32), server_default=sa.text("'GLOBAL'"), nullable=False, comment='作用范围类型（GLOBAL/HOST/SERVICE/ENDPOINT）'),
    sa.Column('scope_id', sa.BigInteger(), nullable=True, comment='作用范围对象 ID'),
    sa.Column('notification_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='通知策略（渠道编码列表与静默配置）'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', name='uq_ops_alert_rule_code'),
    comment='运维告警规则'
    )
    op.create_index('ix_ops_alert_rule_type', 'ops_alert_rule', ['alert_type'], unique=False)
    op.create_table('ops_dashboard',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('dashboard_code', sa.String(length=64), nullable=False, comment='仪表盘编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='仪表盘名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述说明'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否默认仪表盘'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('created_by_username', sa.String(length=64), nullable=True, comment='创建人账号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_code', name='uq_ops_dashboard_code'),
    comment='运维仪表盘'
    )
    op.create_table('ops_environment',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('env_code', sa.String(length=32), nullable=False, comment='环境编码（PRODUCTION/STAGING/TEST/DEVELOPMENT）'),
    sa.Column('env_name', sa.String(length=64), nullable=False, comment='环境名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述说明'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env_code', name='uq_ops_environment_code'),
    comment='运维环境'
    )
    op.create_table('ops_event',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('event_id', sa.String(length=64), nullable=False, comment='事件业务 ID'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='事件类型（SERVICE_DOWN/HOST_OFFLINE/AGENT_OFFLINE/JOB_FAILED/JOB_TIMEOUT/...）'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='事件来源'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='资源 ID'),
    sa.Column('severity', sa.String(length=32), server_default=sa.text("'INFO'"), nullable=False, comment='严重级别（INFO/WARNING/ERROR/CRITICAL）'),
    sa.Column('message', sa.String(length=1000), nullable=True, comment='事件描述'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='事件发生时间（UTC）'),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='结构化扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_ops_event_id'),
    comment='运维事件'
    )
    op.create_index('ix_ops_event_occurred', 'ops_event', ['occurred_at'], unique=False)
    op.create_index('ix_ops_event_trace', 'ops_event', ['trace_id'], unique=False)
    op.create_index('ix_ops_event_type_occurred', 'ops_event', ['event_type', 'occurred_at'], unique=False)
    op.create_table('ops_host_group',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('group_code', sa.String(length=64), nullable=False, comment='分组编码'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='分组名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述说明'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', name='uq_ops_host_group_code'),
    comment='运维主机分组'
    )
    op.create_table('ops_maintenance_window',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('window_code', sa.String(length=64), nullable=False, comment='维护窗口编码'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('reason', sa.String(length=1000), nullable=True, comment='维护原因'),
    sa.Column('scope_type', sa.String(length=32), server_default=sa.text("'GLOBAL'"), nullable=False, comment='作用范围类型（GLOBAL/HOST/SERVICE/ENDPOINT）'),
    sa.Column('scope_id', sa.BigInteger(), nullable=True, comment='作用范围对象 ID'),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False, comment='开始时间（UTC）'),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False, comment='结束时间（UTC）'),
    sa.Column('suppress_alerts', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否抑制告警通知'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('created_by_username', sa.String(length=64), nullable=True, comment='创建人账号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_ops_maintenance_window_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_code', name='uq_ops_maintenance_window_code'),
    comment='运维维护窗口'
    )
    op.create_index('ix_ops_maintenance_window_range', 'ops_maintenance_window', ['starts_at', 'ends_at'], unique=False)
    op.create_table('ops_metric_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('metric_key', sa.String(length=128), nullable=False, comment='指标键'),
    sa.Column('dimension_key', sa.String(length=255), nullable=False, comment='维度键'),
    sa.Column('bucket_at', sa.DateTime(timezone=True), nullable=False, comment='聚合时间桶（UTC，零点）'),
    sa.Column('avg_value', sa.Float(), nullable=True, comment='平均值'),
    sa.Column('min_value', sa.Float(), nullable=True, comment='最小值'),
    sa.Column('max_value', sa.Float(), nullable=True, comment='最大值'),
    sa.Column('sum_value', sa.Float(), nullable=True, comment='求和值'),
    sa.Column('sample_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='采样数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', 'dimension_key', 'bucket_at', name='uq_ops_metric_daily_bucket'),
    comment='运维指标天聚合'
    )
    op.create_index('ix_ops_metric_daily_bucket', 'ops_metric_daily', ['bucket_at'], unique=False)
    op.create_table('ops_metric_definition',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('metric_key', sa.String(length=128), nullable=False, comment='指标键'),
    sa.Column('metric_name', sa.String(length=128), nullable=False, comment='指标名称'),
    sa.Column('metric_type', sa.String(length=32), nullable=False, comment='指标类型（counter/gauge/rate/latency/availability）'),
    sa.Column('unit', sa.String(length=32), nullable=True, comment='单位'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', name='uq_ops_metric_definition_key'),
    comment='运维指标定义'
    )
    op.create_table('ops_metric_hourly',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('metric_key', sa.String(length=128), nullable=False, comment='指标键'),
    sa.Column('dimension_key', sa.String(length=255), nullable=False, comment='维度键'),
    sa.Column('bucket_at', sa.DateTime(timezone=True), nullable=False, comment='聚合时间桶（UTC，整点）'),
    sa.Column('avg_value', sa.Float(), nullable=True, comment='平均值'),
    sa.Column('min_value', sa.Float(), nullable=True, comment='最小值'),
    sa.Column('max_value', sa.Float(), nullable=True, comment='最大值'),
    sa.Column('sum_value', sa.Float(), nullable=True, comment='求和值'),
    sa.Column('sample_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='采样数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', 'dimension_key', 'bucket_at', name='uq_ops_metric_hourly_bucket'),
    comment='运维指标小时聚合'
    )
    op.create_index('ix_ops_metric_hourly_bucket', 'ops_metric_hourly', ['bucket_at'], unique=False)
    op.create_table('ops_metric_sample',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('metric_key', sa.String(length=128), nullable=False, comment='指标键'),
    sa.Column('host_id', sa.BigInteger(), nullable=True, comment='关联主机'),
    sa.Column('service_id', sa.BigInteger(), nullable=True, comment='关联服务'),
    sa.Column('endpoint_id', sa.BigInteger(), nullable=True, comment='关联端点'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('value', sa.Float(), nullable=False, comment='指标值'),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='维度标签'),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False, comment='采集时间（UTC）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    comment='运维指标原始采样'
    )
    op.create_index('ix_ops_metric_sample_collected', 'ops_metric_sample', ['collected_at'], unique=False)
    op.create_index('ix_ops_metric_sample_key_collected', 'ops_metric_sample', ['metric_key', 'collected_at'], unique=False)
    op.create_table('ops_monitor',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('monitor_code', sa.String(length=64), nullable=False, comment='监控对象编码'),
    sa.Column('monitor_name', sa.String(length=128), nullable=False, comment='监控对象名称'),
    sa.Column('monitor_type', sa.String(length=32), nullable=False, comment='监控类型（HOST/SERVICE/API/DATABASE/REDIS/AVAILABILITY/JOB）'),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='目标对象类型'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='目标对象 ID'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='结构化扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_code', name='uq_ops_monitor_code'),
    comment='运维监控对象'
    )
    op.create_index('ix_ops_monitor_type', 'ops_monitor', ['monitor_type'], unique=False)
    op.create_table('ops_notification_channel',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('channel_code', sa.String(length=64), nullable=False, comment='渠道编码'),
    sa.Column('channel_name', sa.String(length=128), nullable=False, comment='渠道名称'),
    sa.Column('channel_type', sa.String(length=32), server_default=sa.text("'WEBHOOK'"), nullable=False, comment='渠道类型（WEBHOOK/EMAIL/WECOM/DINGTALK/FEISHU/SMS）'),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='渠道配置（不含明文凭据）'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_code', name='uq_ops_notification_channel_code'),
    comment='运维通知渠道'
    )
    op.create_table('ops_notification_group',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('group_code', sa.String(length=64), nullable=False, comment='通知组编码'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='通知组名称'),
    sa.Column('channel_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='渠道编码列表'),
    sa.Column('receivers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='接收方列表'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', name='uq_ops_notification_group_code'),
    comment='运维通知组'
    )
    op.create_table('ops_operation_record',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人'),
    sa.Column('operator_username', sa.String(length=64), nullable=True, comment='操作人账号'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作动作'),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='资源类型'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='资源 ID'),
    sa.Column('result', sa.String(length=32), server_default=sa.text("'SUCCESS'"), nullable=False, comment='操作结果（SUCCESS/FAILURE）'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='错误信息'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='操作 IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='操作 UA'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID'),
    sa.Column('before_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='变更前数据'),
    sa.Column('after_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='变更后数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    comment='运维操作记录'
    )
    op.create_index('ix_ops_operation_record_action_time', 'ops_operation_record', ['action', 'created_at'], unique=False)
    op.create_index('ix_ops_operation_record_operator', 'ops_operation_record', ['operator_id'], unique=False)
    op.create_index('ix_ops_operation_record_trace', 'ops_operation_record', ['trace_id'], unique=False)
    op.create_table('ops_dashboard_widget',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False, comment='所属仪表盘'),
    sa.Column('widget_type', sa.String(length=32), nullable=False, comment='组件类型（STAT/LINE/AREA/BAR/TABLE/GAUGE/TOPN/TIMELINE）'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='组件标题'),
    sa.Column('metric_key', sa.String(length=128), nullable=True, comment='指标键'),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='组件渲染选项'),
    sa.Column('position_x', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='栅格列位置'),
    sa.Column('position_y', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='栅格行位置'),
    sa.Column('width', sa.Integer(), server_default=sa.text('6'), nullable=False, comment='栅格宽度'),
    sa.Column('height', sa.Integer(), server_default=sa.text('4'), nullable=False, comment='栅格高度'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['ops_dashboard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='运维仪表盘组件'
    )
    op.create_index('ix_ops_dashboard_widget_dashboard', 'ops_dashboard_widget', ['dashboard_id'], unique=False)
    op.create_table('ops_host',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('hostname', sa.String(length=128), nullable=False, comment='主机名'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名称'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='IP 地址'),
    sa.Column('os_type', sa.String(length=32), nullable=True, comment='操作系统类型'),
    sa.Column('os_version', sa.String(length=64), nullable=True, comment='操作系统版本'),
    sa.Column('cpu_cores', sa.Integer(), nullable=True, comment='CPU 核数'),
    sa.Column('memory_total_mb', sa.BigInteger(), nullable=True, comment='内存总量 MB'),
    sa.Column('disk_total_gb', sa.BigInteger(), nullable=True, comment='磁盘总量 GB'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('host_group_id', sa.BigInteger(), nullable=True, comment='所属主机分组'),
    sa.Column('agent_id', sa.BigInteger(), nullable=True, comment='关联采集 Agent'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False, comment='主机状态（ONLINE/OFFLINE/UNKNOWN/MAINTENANCE）'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='最后上报时间（UTC）'),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='标签'),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='结构化扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['host_group_id'], ['ops_host_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', name='uq_ops_host_hostname'),
    comment='运维主机'
    )
    op.create_index('ix_ops_host_environment', 'ops_host', ['environment'], unique=False)
    op.create_index('ix_ops_host_status', 'ops_host', ['status'], unique=False)
    op.create_table('ops_agent',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('agent_code', sa.String(length=64), nullable=False, comment='Agent 编码'),
    sa.Column('agent_name', sa.String(length=128), nullable=False, comment='Agent 名称'),
    sa.Column('host_id', sa.BigInteger(), nullable=True, comment='所属主机'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Agent 凭证哈希（明文永不落库）'),
    sa.Column('version', sa.String(length=32), nullable=True, comment='Agent 版本'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='上报 IP'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False, comment='Agent 状态（ONLINE/OFFLINE/UPGRADING/UNKNOWN）'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True, comment='最后心跳时间（UTC）'),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True, comment='注册时间（UTC）'),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='结构化扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['host_id'], ['ops_host.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code', name='uq_ops_agent_code'),
    comment='运维采集 Agent'
    )
    op.create_index('ix_ops_agent_status', 'ops_agent', ['status'], unique=False)
    op.create_table('ops_service',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('service_code', sa.String(length=64), nullable=False, comment='服务编码'),
    sa.Column('service_name', sa.String(length=128), nullable=False, comment='服务名称'),
    sa.Column('service_type', sa.String(length=32), server_default=sa.text("'APPLICATION'"), nullable=False, comment='服务类型（APPLICATION/DATABASE/CACHE/WEB/QUEUE）'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('host_id', sa.BigInteger(), nullable=True, comment='承载主机'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False, comment='服务状态（UP/DOWN/DEGRADED/UNKNOWN/MAINTENANCE）'),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True, comment='最近检查时间（UTC）'),
    sa.Column('availability_rate', sa.Float(), nullable=True, comment='可用率'),
    sa.Column('error_rate', sa.Float(), nullable=True, comment='错误率'),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True, comment='平均延迟毫秒'),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='标签'),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='结构化扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['host_id'], ['ops_host.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_code', name='uq_ops_service_code'),
    comment='运维服务'
    )
    op.create_index('ix_ops_service_environment', 'ops_service', ['environment'], unique=False)
    op.create_index('ix_ops_service_status', 'ops_service', ['status'], unique=False)
    op.create_table('ops_agent_heartbeat',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('agent_id', sa.BigInteger(), nullable=False, comment='所属 Agent'),
    sa.Column('cpu_usage', sa.Float(), nullable=True, comment='CPU 使用率'),
    sa.Column('memory_usage', sa.Float(), nullable=True, comment='内存使用率'),
    sa.Column('disk_usage', sa.Float(), nullable=True, comment='磁盘使用率'),
    sa.Column('load1', sa.Float(), nullable=True, comment='Load 1'),
    sa.Column('load5', sa.Float(), nullable=True, comment='Load 5'),
    sa.Column('load15', sa.Float(), nullable=True, comment='Load 15'),
    sa.Column('net_rx_bytes', sa.BigInteger(), nullable=True, comment='网络入流量字节'),
    sa.Column('net_tx_bytes', sa.BigInteger(), nullable=True, comment='网络出流量字节'),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True, comment='运行时长秒'),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False, comment='采集时间（UTC）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.ForeignKeyConstraint(['agent_id'], ['ops_agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='运维 Agent 心跳'
    )
    op.create_index('ix_ops_agent_heartbeat_agent_collected', 'ops_agent_heartbeat', ['agent_id', 'collected_at'], unique=False)
    op.create_table('ops_alert',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('fingerprint', sa.String(length=128), nullable=False, comment='去重指纹'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='命中规则'),
    sa.Column('alert_type', sa.String(length=64), nullable=False, comment='告警类型'),
    sa.Column('severity', sa.String(length=32), server_default=sa.text("'WARNING'"), nullable=False, comment='严重级别'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'TRIGGERED'"), nullable=False, comment='告警状态（TRIGGERED/FIRING/ACKNOWLEDGED/RESOLVED）'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='资源 ID'),
    sa.Column('host_id', sa.BigInteger(), nullable=True, comment='关联主机'),
    sa.Column('service_id', sa.BigInteger(), nullable=True, comment='关联服务'),
    sa.Column('metric_key', sa.String(length=128), nullable=True, comment='指标键'),
    sa.Column('metric_value', sa.Float(), nullable=True, comment='触发时指标值'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='触发阈值'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='告警描述'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='触发时间（UTC）'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='确认时间（UTC）'),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True, comment='确认人'),
    sa.Column('silenced_until', sa.DateTime(timezone=True), nullable=True, comment='静默截止时间（UTC）'),
    sa.Column('silence_reason', sa.String(length=500), nullable=True, comment='静默原因'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='恢复时间（UTC）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['rule_id'], ['ops_alert_rule.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['ops_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_ops_alert_fingerprint'),
    comment='运维告警'
    )
    op.create_index('ix_ops_alert_status_severity', 'ops_alert', ['status', 'severity'], unique=False)
    op.create_index('ix_ops_alert_triggered', 'ops_alert', ['triggered_at'], unique=False)
    op.create_table('ops_availability_check',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('check_code', sa.String(length=64), nullable=False, comment='检查编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='检查名称'),
    sa.Column('check_type', sa.String(length=16), nullable=False, comment='检查类型（HTTP/TCP/DNS/SSL）'),
    sa.Column('target', sa.String(length=500), nullable=False, comment='检查目标'),
    sa.Column('service_id', sa.BigInteger(), nullable=True, comment='关联服务'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('timeout_ms', sa.Integer(), server_default=sa.text('5000'), nullable=False, comment='超时毫秒'),
    sa.Column('interval_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False, comment='检查间隔秒'),
    sa.Column('expected_status', sa.Integer(), nullable=True, comment='HTTP 期望状态码'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['service_id'], ['ops_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_code', name='uq_ops_availability_check_code'),
    comment='运维可用性检查'
    )
    op.create_index('ix_ops_availability_check_type', 'ops_availability_check', ['check_type'], unique=False)
    op.create_table('ops_endpoint',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('endpoint_key', sa.String(length=255), nullable=False, comment='端点唯一键'),
    sa.Column('http_method', sa.String(length=16), nullable=False, comment='HTTP 方法'),
    sa.Column('path_pattern', sa.String(length=500), nullable=False, comment='归一化路径模板'),
    sa.Column('service_id', sa.BigInteger(), nullable=True, comment='所属服务'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'PRODUCTION'"), nullable=False, comment='所属环境'),
    sa.Column('is_monitored', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否纳入监控'),
    sa.Column('request_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='累计请求数'),
    sa.Column('error_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='累计错误数'),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True, comment='平均延迟毫秒'),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True, comment='P95 延迟毫秒'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='最近请求时间（UTC）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['service_id'], ['ops_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_key', name='uq_ops_endpoint_key'),
    comment='运维 API 端点'
    )
    op.create_index('ix_ops_endpoint_service', 'ops_endpoint', ['service_id'], unique=False)
    op.create_table('ops_service_dependency',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('service_id', sa.BigInteger(), nullable=False, comment='依赖方服务'),
    sa.Column('depends_on_service_id', sa.BigInteger(), nullable=False, comment='被依赖服务'),
    sa.Column('dependency_type', sa.String(length=32), server_default=sa.text("'CALLS'"), nullable=False, comment='依赖类型（CALLS/USES/RUNS_ON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（UTC）'),
    sa.ForeignKeyConstraint(['depends_on_service_id'], ['ops_service.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['ops_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'depends_on_service_id', name='uq_ops_service_dependency_pair'),
    comment='运维服务依赖'
    )
    op.create_index('ix_ops_service_dependency_target', 'ops_service_dependency', ['depends_on_service_id'], unique=False)
    op.create_table('ops_alert_history',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('alert_id', sa.BigInteger(), nullable=False, comment='所属告警'),
    sa.Column('from_status', sa.String(length=32), nullable=True, comment='原状态'),
    sa.Column('to_status', sa.String(length=32), nullable=False, comment='新状态'),
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='操作人'),
    sa.Column('actor_username', sa.String(length=64), nullable=True, comment='操作人账号'),
    sa.Column('note', sa.String(length=1000), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.ForeignKeyConstraint(['alert_id'], ['ops_alert.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='运维告警状态历史'
    )
    op.create_index('ix_ops_alert_history_alert', 'ops_alert_history', ['alert_id', 'created_at'], unique=False)
    op.create_table('ops_alert_notification',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('alert_id', sa.BigInteger(), nullable=False, comment='所属告警'),
    sa.Column('channel_id', sa.BigInteger(), nullable=True, comment='通知渠道'),
    sa.Column('channel_code', sa.String(length=64), nullable=False, comment='渠道编码'),
    sa.Column('receiver', sa.String(length=255), nullable=True, comment='接收方'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False, comment='发送状态（PENDING/SENT/FAILED/SKIPPED）'),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='重试次数'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='发送时间（UTC）'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['alert_id'], ['ops_alert.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['ops_notification_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='运维告警通知记录'
    )
    op.create_index('ix_ops_alert_notification_alert', 'ops_alert_notification', ['alert_id'], unique=False)
    op.create_index('ix_ops_alert_notification_status', 'ops_alert_notification', ['status'], unique=False)
    op.create_table('ops_availability_result',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键 ID（雪花算法生成）'),
    sa.Column('check_id', sa.BigInteger(), nullable=False, comment='所属检查'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='延迟毫秒'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP 状态码'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='错误信息'),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='检查结果明细（SSL 颁发者/有效期等）'),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False, comment='检查时间（UTC）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.ForeignKeyConstraint(['check_id'], ['ops_availability_check.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='运维可用性检查结果'
    )
    op.create_index('ix_ops_availability_result_check_time', 'ops_availability_result', ['check_id', 'checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ops_availability_result_check_time', table_name='ops_availability_result')
    op.drop_table('ops_availability_result')
    op.drop_index('ix_ops_alert_notification_status', table_name='ops_alert_notification')
    op.drop_index('ix_ops_alert_notification_alert', table_name='ops_alert_notification')
    op.drop_table('ops_alert_notification')
    op.drop_index('ix_ops_alert_history_alert', table_name='ops_alert_history')
    op.drop_table('ops_alert_history')
    op.drop_index('ix_ops_service_dependency_target', table_name='ops_service_dependency')
    op.drop_table('ops_service_dependency')
    op.drop_index('ix_ops_endpoint_service', table_name='ops_endpoint')
    op.drop_table('ops_endpoint')
    op.drop_index('ix_ops_availability_check_type', table_name='ops_availability_check')
    op.drop_table('ops_availability_check')
    op.drop_index('ix_ops_alert_triggered', table_name='ops_alert')
    op.drop_index('ix_ops_alert_status_severity', table_name='ops_alert')
    op.drop_table('ops_alert')
    op.drop_index('ix_ops_agent_heartbeat_agent_collected', table_name='ops_agent_heartbeat')
    op.drop_table('ops_agent_heartbeat')
    op.drop_index('ix_ops_service_status', table_name='ops_service')
    op.drop_index('ix_ops_service_environment', table_name='ops_service')
    op.drop_table('ops_service')
    op.drop_index('ix_ops_agent_status', table_name='ops_agent')
    op.drop_table('ops_agent')
    op.drop_index('ix_ops_host_status', table_name='ops_host')
    op.drop_index('ix_ops_host_environment', table_name='ops_host')
    op.drop_table('ops_host')
    op.drop_index('ix_ops_dashboard_widget_dashboard', table_name='ops_dashboard_widget')
    op.drop_table('ops_dashboard_widget')
    op.drop_index('ix_ops_operation_record_trace', table_name='ops_operation_record')
    op.drop_index('ix_ops_operation_record_operator', table_name='ops_operation_record')
    op.drop_index('ix_ops_operation_record_action_time', table_name='ops_operation_record')
    op.drop_table('ops_operation_record')
    op.drop_table('ops_notification_group')
    op.drop_table('ops_notification_channel')
    op.drop_index('ix_ops_monitor_type', table_name='ops_monitor')
    op.drop_table('ops_monitor')
    op.drop_index('ix_ops_metric_sample_key_collected', table_name='ops_metric_sample')
    op.drop_index('ix_ops_metric_sample_collected', table_name='ops_metric_sample')
    op.drop_table('ops_metric_sample')
    op.drop_index('ix_ops_metric_hourly_bucket', table_name='ops_metric_hourly')
    op.drop_table('ops_metric_hourly')
    op.drop_table('ops_metric_definition')
    op.drop_index('ix_ops_metric_daily_bucket', table_name='ops_metric_daily')
    op.drop_table('ops_metric_daily')
    op.drop_index('ix_ops_maintenance_window_range', table_name='ops_maintenance_window')
    op.drop_table('ops_maintenance_window')
    op.drop_table('ops_host_group')
    op.drop_index('ix_ops_event_type_occurred', table_name='ops_event')
    op.drop_index('ix_ops_event_trace', table_name='ops_event')
    op.drop_index('ix_ops_event_occurred', table_name='ops_event')
    op.drop_table('ops_event')
    op.drop_table('ops_environment')
    op.drop_table('ops_dashboard')
    op.drop_index('ix_ops_alert_rule_type', table_name='ops_alert_rule')
    op.drop_table('ops_alert_rule')
    # ### end Alembic commands ###
