"""Object key construction and validation.

Keys are generated by the server, never by the client: a client supplied key
would let a caller overwrite someone else's object or escape the storage root
with ``../``. The generated layout is

``[prefix/]<category>/YYYY/MM/DD/<32 hex chars>[.ext]``

which keeps a busy prefix readable in the object storage console (RustFS, MinIO
or whatever else fronts the bucket) and keeps listing costs bounded.
"""

from __future__ import annotations

import datetime
import re
import uuid

_SAFE_SEGMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
_EXTENSION = re.compile(r"^[A-Za-z0-9]{1,8}$")
_UNSAFE = re.compile(r"[\x00-\x1f\x7f\\]")

MAX_OBJECT_KEY_LENGTH = 1024


class InvalidObjectKey(ValueError):
    """Raised when an object key cannot be accepted."""


def sanitize_extension(original_name: str | None) -> str:
    """Return a lower case file extension, or an empty string.

    Only the final extension is kept and anything that is not alphanumeric is
    dropped, so ``"report.tar.gz"`` yields ``gz`` and ``"../../etc/passwd"``
    yields nothing at all.
    """
    if not original_name:
        return ""
    name = original_name.rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
    if "." not in name:
        return ""
    candidate = name.rsplit(".", 1)[1].strip().lower()
    return candidate if _EXTENSION.match(candidate) else ""


def sanitize_category(category: str | None) -> str:
    """Normalize a logical folder name, falling back to ``general``."""
    candidate = (category or "").strip().lower()
    return candidate if _SAFE_SEGMENT.match(candidate) else "general"


def build_object_key(
    *,
    category: str | None = None,
    original_name: str | None = None,
    prefix: str = "",
    now: datetime.datetime | None = None,
) -> str:
    """Build a collision free, root safe object key.

    The date is always UTC: key prefixes are part of the operational contract,
    so they must not shift with the server's timezone.
    """
    moment = now or datetime.datetime.now(datetime.UTC)
    parts = [
        _join_prefix(prefix),
        sanitize_category(category),
        f"{moment:%Y/%m/%d}",
        f"{uuid.uuid4().hex}",
    ]
    extension = sanitize_extension(original_name)
    stem = "/".join(part for part in parts if part)
    return f"{stem}.{extension}" if extension else stem


def _join_prefix(prefix: str) -> str:
    candidate = (prefix or "").strip().strip("/")
    if not candidate:
        return ""
    segments = candidate.split("/")
    if any(not _SAFE_SEGMENT.match(segment) for segment in segments):
        raise InvalidObjectKey(f"storage prefix contains an unsafe segment: {prefix!r}")
    return "/".join(segments)


def validate_object_key(object_key: str) -> str:
    """Reject keys that could escape the storage root.

    Every byte reaching a backend passes through here, including keys recorded
    earlier and read back from the database.
    """
    key = (object_key or "").strip()
    if not key:
        raise InvalidObjectKey("object key is empty")
    if len(key) > MAX_OBJECT_KEY_LENGTH:
        raise InvalidObjectKey("object key exceeds the maximum length")
    if _UNSAFE.search(key):
        raise InvalidObjectKey("object key contains control characters")
    if key.startswith("/"):
        raise InvalidObjectKey("object key must be relative")
    if "\r" in key or "\n" in key:
        raise InvalidObjectKey("object key contains line breaks")
    segments = key.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise InvalidObjectKey("object key contains traversal segments")
    return key


def validate_prefix(prefix: str) -> str:
    """Normalize a listing prefix: no leading slash, trailing slash removed.

    A prefix is not a key. ``exports/`` is how everybody spells it, and the
    empty string legitimately means "everything", so neither is an error.
    """
    candidate = (prefix or "").strip().strip("/")
    if not candidate:
        return ""
    if len(candidate) > MAX_OBJECT_KEY_LENGTH:
        raise InvalidObjectKey("storage prefix exceeds the maximum length")
    if _UNSAFE.search(candidate) or "\r" in candidate or "\n" in candidate:
        raise InvalidObjectKey("storage prefix contains control characters")
    segments = candidate.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise InvalidObjectKey("storage prefix contains traversal segments")
    return candidate


__all__ = [
    "MAX_OBJECT_KEY_LENGTH",
    "InvalidObjectKey",
    "build_object_key",
    "sanitize_category",
    "sanitize_extension",
    "validate_object_key",
    "validate_prefix",
]
