"""Unit tests for agent credential handling.

The plain token is generated by the service, returned exactly once to the
operator who registers the agent, hashed with ``sha256`` and then discarded: it
must never be persisted, never audited and never logged. Only ``agent_code``
reaches the audit trail.

A heartbeat is the other half of the rule: the agent authenticates with its own
credential, and every rejection answers with the same ``401`` so the endpoint
cannot be used as an oracle.

The repository is stubbed, so no database is touched.
"""

from __future__ import annotations

import datetime
import hashlib
import json
from types import SimpleNamespace
from typing import Any

import pytest

from app.admin.audit.model import SysOperationLog
from app.core.config import Settings
from app.core.exceptions import AuthenticationError, ConflictError
from app.ops.agents.schema import AgentCreateRequest, AgentHeartbeatRequest
from app.ops.agents.service import AgentService
from app.shared.auth.context import Principal

_NOW = datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC)


class _FakeSession:
    """A session that records what the service appended and committed."""

    def __init__(self) -> None:
        self.added: list[Any] = []
        self.commits = 0

    async def commit(self) -> None:
        self.commits += 1

    async def flush(self) -> None:
        return None

    def add(self, row: Any) -> None:
        self.added.append(row)

    def add_all(self, rows: list[Any]) -> None:
        self.added.extend(rows)

    async def execute(self, *_args: Any, **_kwargs: Any) -> Any:
        raise AssertionError("the agent credential tests must not reach the database")

    def operation_metadata(self) -> list[dict[str, Any]]:
        return [
            dict(row.metadata_payload or {})
            for row in self.added
            if isinstance(row, SysOperationLog)
        ]


class _RecordingAudit:
    """Stands in for :class:`OpsAuditRecorder` and records every payload."""

    def __init__(self) -> None:
        self.actions: list[str] = []
        self.payloads: list[dict[str, Any]] = []

    async def record(self, *, action: str, **kwargs: Any) -> None:
        self.actions.append(action)
        self.payloads.append(kwargs)


class _StubAgentRepository:
    """The agent reads and writes the service touches, in memory."""

    def __init__(self, agent: SimpleNamespace | None = None) -> None:
        self._agent = agent
        self.created: list[dict[str, Any]] = []
        self.updates: list[dict[str, Any]] = []
        self.heartbeats: list[dict[str, Any]] = []
        self.samples: list[list[dict[str, Any]]] = []

    async def get_by_code(self, agent_code: str) -> SimpleNamespace | None:
        if self._agent is None:
            return None
        return self._agent if self._agent.agent_code == agent_code else None

    async def create(self, **fields: Any) -> SimpleNamespace:
        self.created.append(dict(fields))
        return SimpleNamespace(**fields, ip_address=None, last_heartbeat_at=None)

    async def update(self, row: SimpleNamespace, **fields: Any) -> None:
        for key, value in fields.items():
            setattr(row, key, value)
        self.updates.append(dict(fields))

    async def add_heartbeat(self, **fields: Any) -> SimpleNamespace:
        self.heartbeats.append(dict(fields))
        return SimpleNamespace(**fields)

    async def add_metric_samples(self, rows: list[dict[str, Any]]) -> None:
        self.samples.append(rows)

    async def get_host(self, host_id: int) -> SimpleNamespace | None:
        raise AssertionError("the credential tests use an agent without a host")


def _actor() -> Principal:
    return Principal(
        subject_id=7,
        subject_type="admin",
        session_id=1,
        username="ops-admin",
        display_name="ops admin",
    )


def _sha256(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _agent(**overrides: Any) -> SimpleNamespace:
    fields: dict[str, Any] = {
        "id": 7001,
        "agent_code": "AGENT_1",
        "agent_name": "agent one",
        "host_id": None,
        "token_hash": _sha256("not-the-real-token"),
        "version": "1.0.0",
        "status": "UNKNOWN",
        "enabled": True,
        "ip_address": None,
        "last_heartbeat_at": None,
        "registered_at": _NOW,
        "metadata_payload": None,
        "created_at": _NOW,
        "updated_at": _NOW,
    }
    fields.update(overrides)
    return SimpleNamespace(**fields)


def _service(
    agent: SimpleNamespace | None = None,
) -> tuple[AgentService, _StubAgentRepository, _FakeSession, _RecordingAudit]:
    session = _FakeSession()
    service = AgentService(session, Settings(_env_file=None))
    repository = _StubAgentRepository(agent)
    audit = _RecordingAudit()
    service._repository = repository  # type: ignore[attr-defined]
    service._audit = audit  # type: ignore[attr-defined]
    return service, repository, session, audit


@pytest.mark.asyncio()
async def test_registration_stores_only_the_hash_of_the_token() -> None:
    service, repository, _session, _audit = _service()

    response = await service.register_agent(
        _actor(),
        AgentCreateRequest(agent_code="AGENT_1", agent_name="agent one"),  # type: ignore[arg-type]
    )

    stored = repository.created[0]
    assert response.token
    assert stored["token_hash"] == _sha256(response.token)
    assert stored["token_hash"] != response.token
    assert "token" not in stored, "the plain token must have no column of its own"
    assert [key for key in stored if "token" in key] == ["token_hash"]
    assert response.token not in json.dumps(stored, default=str)


@pytest.mark.asyncio()
async def test_registration_never_writes_the_token_into_the_audit_trail() -> None:
    service, repository, session, audit = _service()

    response = await service.register_agent(
        _actor(),
        AgentCreateRequest(agent_code="AGENT_1", agent_name="agent one"),  # type: ignore[arg-type]
    )

    assert audit.actions == ["OPS_AGENT_REGISTER"]
    trail = json.dumps(audit.payloads, default=str) + json.dumps(
        session.operation_metadata(), default=str
    )
    assert response.token not in trail
    assert audit.payloads[0]["after_data"]["agent_code"] == "AGENT_1"
    assert session.operation_metadata() == [{}]
    assert repository.created[0]["agent_code"] == "AGENT_1"


@pytest.mark.asyncio()
async def test_the_registered_token_is_the_only_one_that_works() -> None:
    service, repository, session, _audit = _service()
    registered = await service.register_agent(
        _actor(),
        AgentCreateRequest(agent_code="AGENT_1", agent_name="agent one"),  # type: ignore[arg-type]
    )

    agent = _agent(token_hash=_sha256(registered.token), status="OFFLINE")
    service, repository, session, _audit = _service(agent)

    accepted = await service.record_heartbeat(
        AgentHeartbeatRequest(  # type: ignore[arg-type]
            agent_code="AGENT_1",
            token=registered.token,
            cpu_usage=12.5,
            memory_usage=40.0,
            disk_usage=70.0,
            collected_at=_NOW,
        )
    )

    assert accepted.agent_code == "AGENT_1"
    assert accepted.status == "ONLINE"
    assert agent.last_heartbeat_at == _NOW
    assert agent.status == "ONLINE"
    assert len(repository.heartbeats) == 1
    assert repository.heartbeats[0]["agent_id"] == 7001
    assert accepted.metric_keys == [
        "host.cpu_usage",
        "host.memory_usage",
        "host.disk_usage",
    ]
    assert session.commits == 1


@pytest.mark.asyncio()
async def test_a_wrong_token_is_rejected_and_records_nothing() -> None:
    agent = _agent(token_hash=_sha256("the-real-token"), status="OFFLINE")
    service, repository, session, _audit = _service(agent)

    with pytest.raises(AuthenticationError):
        await service.record_heartbeat(
            AgentHeartbeatRequest(  # type: ignore[arg-type]
                agent_code="AGENT_1", token="the-wrong-token"
            )
        )

    assert repository.heartbeats == []
    assert repository.updates == []
    assert agent.last_heartbeat_at is None
    assert agent.status == "OFFLINE"
    assert session.commits == 0


@pytest.mark.asyncio()
async def test_a_disabled_agent_is_rejected_even_with_a_valid_token() -> None:
    agent = _agent(token_hash=_sha256("the-real-token"), enabled=False)
    service, repository, _session, _audit = _service(agent)

    with pytest.raises(AuthenticationError):
        await service.record_heartbeat(
            AgentHeartbeatRequest(  # type: ignore[arg-type]
                agent_code="AGENT_1", token="the-real-token"
            )
        )

    assert repository.heartbeats == []


@pytest.mark.asyncio()
async def test_an_unknown_agent_code_is_rejected_like_a_wrong_token() -> None:
    """No oracle: an unknown code and a wrong token answer identically."""
    service, repository, _session, _audit = _service(_agent())

    with pytest.raises(AuthenticationError):
        await service.record_heartbeat(
            AgentHeartbeatRequest(  # type: ignore[arg-type]
                agent_code="AGENT_UNKNOWN", token="the-real-token"
            )
        )

    assert repository.heartbeats == []


@pytest.mark.asyncio()
async def test_a_heartbeat_without_credentials_is_rejected() -> None:
    service, repository, _session, _audit = _service(_agent())

    with pytest.raises(AuthenticationError):
        await service.record_heartbeat(AgentHeartbeatRequest())  # type: ignore[arg-type]

    assert repository.heartbeats == []


@pytest.mark.asyncio()
async def test_the_heartbeat_log_never_carries_the_plain_token() -> None:
    agent = _agent(token_hash=_sha256("the-real-token"))
    service, _repository, session, _audit = _service(agent)

    await service.record_heartbeat(
        AgentHeartbeatRequest(  # type: ignore[arg-type]
            agent_code="AGENT_1", token="the-real-token", cpu_usage=12.5
        )
    )

    metadata = session.operation_metadata()
    assert [row["agent_code"] for row in metadata] == ["AGENT_1"]
    assert "the-real-token" not in json.dumps(metadata, default=str)
    assert _sha256("the-real-token") not in json.dumps(metadata, default=str)


@pytest.mark.asyncio()
async def test_a_duplicate_agent_code_is_refused() -> None:
    service, repository, _session, audit = _service(_agent())

    with pytest.raises(ConflictError):
        await service.register_agent(
            _actor(),
            AgentCreateRequest(agent_code="AGENT_1", agent_name="clone"),  # type: ignore[arg-type]
        )

    assert repository.created == []
    assert audit.actions == []


@pytest.mark.asyncio()
async def test_the_agent_response_never_exposes_the_hash() -> None:
    service, _repository, _session, _audit = _service()

    response = await service.register_agent(
        _actor(),
        AgentCreateRequest(agent_code="AGENT_1", agent_name="agent one"),  # type: ignore[arg-type]
    )

    dumped = response.model_dump()
    assert "token_hash" not in dumped
    assert set(dumped) >= {"id", "agent_code", "agent_name", "status", "enabled", "token"}
